# Generated by Django 5.2.13 on 2026-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputRefDataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_liabs', models.CharField(max_length=32)),
                ('num_and_name', models.CharField(max_length=255)),
                ('minor_account', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('sub_cat', models.CharField(blank=True, max_length=255)),
                ('sub_sub_cat', models.CharField(blank=True, max_length=255)),
                ('currency_scope', models.CharField(max_length=16)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assets_liabs', 'num_and_name', 'minor_account', 'account_name', 'sub_cat', 'sub_sub_cat', 'currency_scope'), name='uq_input_refdata_row_identity')],
            },
        ),
        migrations.CreateModel(
            name='ReportingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=64)),
                ('account', models.CharField(max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group_type', 'account'), name='uq_reporting_group_type_account')],
            },
        ),
    ]
