# Generated by Django 5.2.13 on 2026-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrefdatarow',
            name='calc_key_1',
            field=models.CharField(db_index=True, default='', max_length=1024),
        ),
    ]
