# Generated by Django 5.2.13 on 2026-04-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_inputrefdatarow_calc_key_1'),
    ]

    @staticmethod
    def _backfill_helper(apps, schema_editor):
        InputRefDataRow = apps.get_model("ui", "InputRefDataRow")
        # Batch update: compute helper from existing values
        for row in InputRefDataRow.objects.all().only("id", "calc_key_1", "currency_scope"):
            helper = f"{row.calc_key_1}{row.currency_scope}"
            InputRefDataRow.objects.filter(id=row.id).update(helper=helper)

    operations = [
        migrations.AddField(
            model_name='inputrefdatarow',
            name='helper',
            field=models.CharField(db_index=True, default='', max_length=1050),
        ),
        migrations.RunPython(_backfill_helper, migrations.RunPython.noop),
    ]
