# Generated by Django 5.2.13 on 2026-04-22 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_inputrefdatarow_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrefdatarow',
            name='reporting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_refdata_rows', to='ui.reportinggroup'),
        ),
    ]
