# Generated by Django 5.2.13 on 2026-04-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_inputrefdatarow_reporting_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrefdatarow',
            name='reporting_group_imported',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
