# Generated by Django 5.2.13 on 2026-04-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_inputrefdatarow_reporting_group_imported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputrefdatarow',
            name='reporting_group',
        ),
    ]
