# Generated by Django 5.2.13 on 2026-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_remove_inputrefdatarow_reporting_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BsIsMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_sheet', models.TextField()),
                ('prof_and_loss', models.TextField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('balance_sheet', 'prof_and_loss'), name='uq_bs_is_mapping_pair')],
            },
        ),
    ]
