# Generated by Django 5.2.13 on 2026-04-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_bsismapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedDataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(db_index=True)),
                ('month_english_name', models.CharField(blank=True, default='', max_length=32)),
                ('line_code', models.CharField(blank=True, default='', max_length=64)),
                ('trial_balance_name', models.CharField(blank=True, default='', max_length=255)),
                ('tb_name2', models.CharField(blank=True, default='', max_length=255)),
                ('business_unit_name', models.CharField(blank=True, default='', max_length=128)),
                ('branch_code_name', models.CharField(blank=True, default='', max_length=128)),
                ('rm_name', models.CharField(blank=True, default='', max_length=128)),
                ('assets_liabs', models.CharField(blank=True, default='', max_length=32)),
                ('num_and_name', models.CharField(blank=True, default='', max_length=255)),
                ('minor_account', models.CharField(blank=True, default='', max_length=255)),
                ('major_account', models.CharField(blank=True, default='', max_length=255)),
                ('currency_type', models.CharField(blank=True, default='', max_length=16)),
                ('value_raw', models.CharField(blank=True, default='', max_length=64)),
                ('tenor', models.CharField(blank=True, default='', max_length=64)),
                ('sub_cat', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('row_number',), name='uq_consolidated_row_number')],
            },
        ),
    ]
