# Generated by Django 5.2.13 on 2026-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_consolidateddatarow'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrefdatarow',
            name='lookup',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='inputrefdatarow',
            name='target_rate',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inputrefdatarow',
            name='tenor_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='inputrefdatarow',
            name='tenor_units',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
