# Generated by Django 5.2.13 on 2026-04-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_inputrefdatarow_lookup_inputrefdatarow_target_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrefdatarow',
            name='tenor_days',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
