# Generated by Django 5.2.13 on 2026-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_inputrefdatarow_tenor_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputrefdatarow',
            name='ftp_rate',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
