# Generated by Django 5.2.13 on 2026-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_inputrefdatarow_ftp_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsismapping',
            name='asset_liab_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='bsismapping',
            name='pnl_attributed',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='bsismapping',
            name='pnl_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='bsismapping',
            name='proportion',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=18),
        ),
    ]
