# Generated by Django 5.2.13 on 2026-04-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_bsismapping_asset_liab_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidateddatarow',
            name='acct_num',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='actual_rate',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='average_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='bsislookup',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3072),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='ftp_int',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='ftp_rate',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='gross_int',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='input_refdata_lookup',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3072),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='lookup1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='lookup2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='pnl_interest',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='pnl_item',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='reporting_group',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='sub_sub_cat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='target_rate',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='consolidateddatarow',
            name='tenor_days',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
