# Generated by Django 5.2.13 on 2026-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_consolidateddatarow_acct_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('LCY', 'LCY'), ('FCY', 'FCY')], max_length=3)),
                ('component', models.CharField(choices=[('BASE', 'Base curve'), ('SPREAD', 'Liquidity spread')], max_length=10)),
                ('tenor_days', models.IntegerField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=12, max_digits=18)),
            ],
            options={
                'indexes': [models.Index(fields=['currency', 'component', 'tenor_days'], name='idx_curve_point_lookup')],
                'constraints': [models.UniqueConstraint(fields=('currency', 'component', 'tenor_days'), name='uq_curve_point_currency_component_tenor')],
            },
        ),
    ]
