# Generated by Django 5.2.13 on 2026-04-24 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_curvepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_key', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['table_key', '-created_at'], name='idx_dataevent_latest')],
            },
        ),
    ]
